---
- name: Create in-memory Group
  hosts: all
  ignore_errors: true
  tasks:
    
    - name: Create In Memory Group
      add_host:
        name: "{{ item }}"
        group: 'failed_hosts'
      when: _failed_status != 'pass'
      loop: "{{ play_hosts }}"


- name: Send SlackNotify
  hosts: failed_hosts
  vars:
    ansible_connection: local
  tasks:
    - name: DEBUG >> Output all Hosts
      debug:
        msg: "{{ inventory_hostname }}"

    - name: test slack
      slack:
        username: 'AWX'
        msg: "Failed Notification for Host {{ inventory_hostname }}"
        token: "TKA7NDKT4/BQV99CWSV/YBTnlxmy11u3RmlhnbNEzXWl"